feat: handle failures in individual update checks more gracefully #147

diff --git a/package/contents/tools/sh/utils b/package/contents/tools/sh/utils
--- a/package/contents/tools/sh/utils
+++ b/package/contents/tools/sh/utils
@@ -215,6 +215,7 @@ rss() {
     trap cleanup EXIT
 
     local newsFile="$configDir/news.json"
+    local errors=""
 
     if [[ ! -s "$newsFile" ]] \
     || ! jq -e '.' "$newsFile" >/dev/null 2>&1 \
@@ -224,15 +225,21 @@ rss() {
 
     for url in "$@"; do
         local rssFile=$(mktemp "$tempDir/XXXXXX.xml")
-        curl -s -o "$rssFile" --connect-timeout 5 --retry 2 --max-time 60 --url "$url" 2>/dev/null
-        xmllint --noout "$rssFile" 2>/dev/null || { echo $url; exit 1; }
+        curl -s -o "$rssFile" --connect-timeout 5 --retry 2 --max-time 10 --url "$url" 2>/dev/null
+        xmllint --noout "$rssFile" 2>/dev/null || {
+            errors+="$url "
+            continue
+        }
 
         local title=$(xmllint --xpath "string(/rss/channel/title)" $rssFile)
         local article=$(xmllint --xpath "string(/rss/channel/item[1]/title)" $rssFile)
         local date=$(date -d "$(xmllint --xpath 'string(/rss/channel/item[1]/pubDate)' $rssFile)" +"%d.%m.%Y | %H:%M")
         local link=$(xmllint --xpath "string(/rss/channel/item[1]/link)" $rssFile)
 
-        [[ -z "$title" || -z "$article" || -z "$date" || -z "$link" ]] && { echo $url; exit 1; }
+        [[ -z "$title" || -z "$article" || -z "$date" || -z "$link" ]] && {
+            errors+="$url "
+            continue
+        }
 
         while (( $(jq "[.[] | select(.title == \"$title\")] | length" "$newsFile") > newsKeep )); do
             index=$(jq --arg title "$title" 'to_entries | reverse | map(select(.value.title == $title)) | .[0].key' $newsFile)
@@ -248,6 +255,13 @@ rss() {
     updateJson $newsFile "$(jq 'sort_by(.date | strptime("%d.%m.%Y | %H:%M") | mktime) | reverse' $newsFile)"
 
     jq . $newsFile
+
+    if [[ -n "$errors" ]]; then
+        errors="$NEWS_ERR: ${errors// /, }"
+        errors="${errors%, }"
+        echo "$errors" >&2
+        exit 1
+    fi
 }
 
 sync_dbs() {
@@ -257,6 +271,7 @@ sync_dbs() {
     }
     db_conf="$(pacman-conf DBPath)"
     dbPath="${TMPDIR:-/tmp}/checkup-db-${UID}"
+    test -f $dbPath/db.lck && rm -f $dbPath/db.lck
     mkdir -p "$dbPath"
     ln -sf "${db_conf}/local" "$dbPath" &> /dev/null
     ! fakeroot -- pacman -Sy --dbpath "$dbPath" --logfile /dev/null 2>/dev/null && {
